variables:
  COMPONENT_PROJECT_ID: 466
  COMPONENT_PROJECT_PIPELINE_TRIGGER: 5ec45d577ae29bc712f6e438d62e31
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

before_script:
  - python3 -V && python3 -m venv venv && source venv/bin/activate
  - COUCHDB_TEST_CONTAINER=`docker run -d -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=admin -p 5984:5984 couchdb:1.7.2`
after_script:
  - docker rm -f $COUCHDB_TEST_CONTAINER

test:
  script:
    - pip install .[test]
    - pytest tests/ && python setup.py sdist
    - "curl -XPOST --form token=$COMPONENT_PROJECT_PIPELINE_TRIGGER --form ref=master https://gitlab.quintagroup.com/api/v4/projects/$COMPONENT_PROJECT_ID/trigger/pipeline"
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  tags:
    - spage
  only:
    - master
