db:
    host: ${options['host']}
    name: ${options['name']}
    port: ${options['port']}

logging:
    version: 1
    disable_existing_loggers: False

    formatters:
      simple:
        format: '%(asctime)s  %(name)-10s %(levelname)-7s %(message)s'

    handlers:
        file:
            class: logging.handlers.RotatingFileHandler
            formatter: simple
            filename: ${parts.buildout.directory}/var/log/bridge.log
        console:
            class: logging.StreamHandler
            formatter: simple
    packer:
        level: DEBUG
        handlers:
            - file
            - console

    root:
        level: DEBUG
        handlers:
            - file
            - console