"""initial

Revision ID: a9e9bebc0fcd
Revises: 
Create Date: 2018-11-07 20:08:21.538520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9e9bebc0fcd'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocid', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('released', sa.Boolean(), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_releases'))
    )
    op.create_index('date_released', 'releases', ['date'], unique=False)
    op.create_index('ocids', 'releases', ['ocid'], unique=True)
    op.create_index('unreleased', 'releases', ['released'], unique=False, postgresql_where=sa.text('released = false'))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unreleased', table_name='releases')
    op.drop_index('ocids', table_name='releases')
    op.drop_index('date_released', table_name='releases')
    op.drop_table('releases')
    # ### end Alembic commands ###
