"""second

Revision ID: 01a9a6e058f7
Revises: a9e9bebc0fcd
Create Date: 2018-11-07 20:10:05.120158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a9a6e058f7'
down_revision = 'a9e9bebc0fcd'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
