"""Initial

Revision ID: df7bef1d65ac
Revises: 
Create Date: 2018-11-15 17:35:12.346736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df7bef1d65ac'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('ocid', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ocid', name=op.f('pk_records'))
    )
    op.create_index('date-record', 'records', ['ocid', sa.text('date DESC')], unique=False)
    op.create_table('releases',
    sa.Column('release_id', sa.String(), nullable=False),
    sa.Column('ocid', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('last_published', sa.DateTime(), nullable=True),
    sa.Column('value', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['ocid'], ['records.ocid'], name=op.f('fk_releases_ocid_records')),
    sa.PrimaryKeyConstraint('release_id', name=op.f('pk_releases'))
    )
    op.create_index('date', 'releases', [sa.text('date DESC')], unique=False)
    op.create_index('ocids', 'releases', ['ocid'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ocids', table_name='releases')
    op.drop_index('date', table_name='releases')
    op.drop_table('releases')
    op.drop_index('date-record', table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###
