"""rename id->release_id

Revision ID: 85364c9cbe34
Revises: 
Create Date: 2018-11-08 20:53:53.744408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85364c9cbe34'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releases',
    sa.Column('release_id', sa.String(), nullable=False),
    sa.Column('ocid', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('in_static', sa.Boolean(), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('release_id', name=op.f('pk_releases'))
    )
    op.create_index('date_released', 'releases', ['date'], unique=False)
    op.create_index('ids', 'releases', ['release_id'], unique=False)
    op.create_index('ocids', 'releases', ['ocid'], unique=False)
    op.create_index('unreleased', 'releases', ['in_static'], unique=False, postgresql_where=sa.text('in_static = false'))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unreleased', table_name='releases')
    op.drop_index('ocids', table_name='releases')
    op.drop_index('ids', table_name='releases')
    op.drop_index('date_released', table_name='releases')
    op.drop_table('releases')
    # ### end Alembic commands ###
