"""non unique ocids

Revision ID: 14b492cfbe32
Revises: 01a9a6e058f7
Create Date: 2018-11-08 17:24:49.327476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b492cfbe32'
down_revision = '01a9a6e058f7'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ocids', table_name='releases')
    op.create_index('ocids', 'releases', ['ocid'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ocids', table_name='releases')
    op.create_index('ocids', 'releases', ['ocid'], unique=True)
    # ### end Alembic commands ###
