"""text ids

Revision ID: accbc8a0021d
Revises: 14b492cfbe32
Create Date: 2018-11-08 19:08:47.409702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'accbc8a0021d'
down_revision = '14b492cfbe32'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
