"""simpler ids

Revision ID: 8b0542dab575
Revises: 80ccbf3323e8
Create Date: 2019-03-08 17:33:25.682448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0542dab575'
down_revision = '80ccbf3323e8'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'ocid', new_column_name='id')
    op.drop_index('date-record', table_name='records')
    op.create_index('date-record', 'records', ['id', sa.text('date DESC')], unique=False)
    op.drop_constraint('fk_releases_ocid_records', 'releases', type_='foreignkey')
    op.create_foreign_key(op.f('fk_releases_ocid_records'), 'releases', 'records', ['ocid'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'id', new_column_name='ocid')
    op.drop_constraint(op.f('fk_releases_ocid_records'), 'releases', type_='foreignkey')
    op.create_foreign_key('fk_releases_ocid_records', 'releases', 'records', ['ocid'], ['ocid'])
    op.drop_index('date-record', table_name='records')
    op.create_index('date-record', 'records', ['ocid', 'date'], unique=False)
    # ### end Alembic commands ###
