"""compiledRelease

Revision ID: f002646b0606
Revises: df7bef1d65ac
Create Date: 2019-03-08 16:47:40.321153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f002646b0606'
down_revision = 'df7bef1d65ac'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('compiled_release', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'compiled_release')
    # ### end Alembic commands ###
