"""indexes

Revision ID: e8506663a5d8
Revises: 
Create Date: 2019-03-18 18:19:28.629330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8506663a5d8'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('compiled_release', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records'))
    )
    op.create_index('date-record', 'records', ['id', sa.text('date DESC')], unique=False)
    op.create_index('record-timestamp', 'records', ['timestamp'], unique=False)
    op.create_index('record-timestamp-id', 'records', [sa.text('timestamp ASC'), 'id'], unique=False)
    op.create_table('releases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ocid', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['ocid'], ['records.id'], name=op.f('fk_releases_ocid_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_releases'))
    )
    op.create_index('date', 'releases', [sa.text('date DESC')], unique=False)
    op.create_index('ocids', 'releases', ['ocid'], unique=False)
    op.create_index('release-timestamp', 'releases', ['timestamp'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('release-timestamp', table_name='releases')
    op.drop_index('ocids', table_name='releases')
    op.drop_index('date', table_name='releases')
    op.drop_table('releases')
    op.drop_index('record-timestamp-id', table_name='records')
    op.drop_index('record-timestamp', table_name='records')
    op.drop_index('date-record', table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###
