"""indexes

Revision ID: 111b3500ad0b
Revises: f7defbda6a36
Create Date: 2019-03-18 13:07:01.611051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111b3500ad0b'
down_revision = 'f7defbda6a36'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
