"""timestamp

Revision ID: 83318be22486
Revises: f002646b0606
Create Date: 2019-03-08 17:13:06.902887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '83318be22486'
down_revision = 'f002646b0606'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('timestamp', sa.TIMESTAMP(), nullable=True))
    op.create_index('record-timestamp', 'records', ['timestamp'], unique=False)
    op.add_column('releases', sa.Column('timestamp', sa.TIMESTAMP(), nullable=True))
    op.create_index('release-timestamp', 'releases', ['timestamp'], unique=False)
    op.drop_column('releases', 'last_published')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('last_published', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index('release-timestamp', table_name='releases')
    op.drop_column('releases', 'timestamp')
    op.drop_index('record-timestamp', table_name='records')
    op.drop_column('records', 'timestamp')
    # ### end Alembic commands ###
